### ISSUE TITLE
Lack of files in newest version

### ISSUE THREAD

**Issue by wszydlak** [zeplin/cli-connect-angular-plugin#11]
Version 0.1.5 in npm registry contains no js files.
Probably something went wrong when publishing this version to registry.
This means cli-connect-angular-plugin does not work.

![image](https://user-images.githubusercontent.com/6583977/114505303-762dac00-9c30-11eb-95fb-5fabd97b72fd.png)

Version 0.1.4 is OK

**Comment by yuqu** [comment]
Sorry about the inconvenience, this is completely my mistake. Latest commits included package.json on runtime which caused contents in `dist/*` folder to be replaced in under `dist/src/*`. 

Fixed .npmignore file to ignore `src` on the root. 0.1.6 is published with the files.

Thanks.
