### ISSUE TITLE
Component snippet or description not found on v0.1.7

### ISSUE THREAD

**Issue by ofirrifo** [zeplin/cli-connect-angular-plugin#15]
Im using the  zeplin connect command in order to show in zeplin the component tag.
I'm working on angular project and I install both 
`npm install -g @zeplin/cli ` and `npm install -g @zeplin/cli-connect-angular-plugin `

On my project I have in the root this folder `.zeplin` and inside I have this file `components.json`
with this step:

```
{
  "plugins" : [{
    "name": "@zeplin/cli-connect-angular-plugin",
    "config": {
      "useFullSnippet": true,
      "useFullDescription": true
    }
  }],
  "projects": [],
  "styleguides": ["My-styleguides-ID"],
  "components": [
    {
      "path": "projects/singularity-ui-lib/src/lib/modules/popups/dialog-footer/dialog-footer/dialog-footer.component.ts",
      "zeplinNames": ["Dialogue/footer", "Dialogues/dialogue-footer"],
      "sing": {
        "urlPath": "sing-dialog-footer"
      }
    },
  ],
  "links": [
    {
      "name": "SOL Components",
      "type": "sol",
      "url": "https://sol-components-us-east-1-int.s1.guru/sol-show-case"
    }
  ]
}

```

I'm executing this command `zeplin connect  @zeplin/cli-connect-angular-plugin`
and I see the result 
```
Zeplin CLI - v1.1.12

Connecting all Connected Components into Zeplin…
🦄 Components successfully connected to components in Zeplin.
```

until now I was able to see the component selector  tag 

for example `<sing-dialog-footer></sing-dialog-footer>`

But for some reason it not show it any more and I see the below

```
dialog-footer.component
projects/singularity-ui-lib/src/lib/modules/popups/dialog-footer/dialog-footer/dialog-footer.component.ts
No description or code snippet.
```

**Comment by yuqu** [comment]
Hey @ofirrifo , could you share the angular plugin version currently installed?

**Comment by ofirrifo** [comment]
@yuqu 

My global packages ` npm ls -g --depth=0 `
```                                  
/Users/ofirf 1/.nvm/versions/node/v14.15.5/lib
├── @angular/cli@12.0.3
├── @zeplin/cli@1.1.12
├── @zeplin/cli-connect-angular-plugin@0.1.7
├── npm@6.14.11
└── sass-migrator@1.4.3

```

**Comment by ofirrifo** [comment]
@yuqu I downgrade to 0.1.6 and now it back to work

**Comment by ofirrifo** [comment]
@yuqu 
First thanks for the fast answer and additional solution :)

is it will be fixed in next version ?

**Comment by yuqu** [comment]
Yes, I cannot give a timeline for the release but we will try to fix it. Let's keep the issue open until then. BTW, changed the issue title for visibility.
