### ISSUE TITLE
Getting CompoDoc Errors when installing

### ISSUE THREAD

**Issue by dperciful** [zeplin/cli-connect-angular-plugin#6]
sudo npm install -g @zeplin/cli-connect-angular-plugin
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t https://github.com/yuqu/compodoc.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/yuqu/compodoc.git/': Failed to connect to github.com port 443: Operation timed out
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donald/.npm/_logs/2020-04-16T20_50_07_089Z-debug.log

**Comment by yuqu** [comment]
Hi @dperciful,

It seems your git client cannot connect to GitHub. Do you have any git configuration or network limitations that would cause it?

**Comment by dperciful** [comment]
Duh good call.  Let me see if that's the issue.   AWESOME JOB ON THIS BY THE WAY!

**Comment by yuqu** [comment]
Hey @dperciful, could you resolve the problem?

**Comment by ogalimov** [comment]
The main problem here are the dependencies of the project:
 "dependencies": {
    "@compodoc/compodoc": "git+https://github.com/yuqu/compodoc.git#develop",
    "fs-extra": "^8.1.0",
    "pug": "^2.0.4"
  }

It is highly unusuall to reference a git repository as a dependency version. 

In this case version "^1.1.11" would do perfectly fine,

**Comment by yuqu** [comment]
@ogalimov It was intended. The repository contains a forked version of the library and it has some modifications to make it work for us. Changing it to 1.1.11 won't work since the plugin is dependent on the interface provided by the forked version. 

I was planning to open a PR on compodoc. That's why I kept it as git dependency instead of publishing the forked version on npm. I think the project was inactive for the last year but I know that the developer will be working on a rewrite of the library on these days.

@dperciful I believe you already made it work. You can reopen if you are still having trouble.

**Comment by pascal-puetz** [comment]
@yuqu Hi there, we are still running into the exact same problem as described by ogalimov. Unfortunately, we are not allowed, by company policy, to directly access the forked compodoc version from our build servers. Is there any chance you can fix the dependency so that we can use this plugin?

**Comment by yuqu** [comment]
Sorry to hear that. The current flow of how plugins works requires the changes on forked version. 

I'll consider it, with the recent changes the CLI, we may refactor the plugin to comply with compodoc's vanilla version. Reopening the issue to track it.

**Comment by pascal-puetz** [comment]
Thanks for the quick response! Making the plugin comply with vanilla compodoc would be the best solution of course. As a workaround until then, would it be possible for you to publish the forked version to npm and update the dependency here? 
We just introduced chromatic into our workflow and having that play as nicely as possible with our zeplin workflow would be a huge benefit for us.

**Comment by yuqu** [comment]
Thanks to @Helehelehele, it is fixed with v0.1.7 🎉
